version: "3.7"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: agent
      POSTGRES_DB: agentdb
    ports: ["5432:5432"]
  zookeeper:
    image: wurstmeister/zookeeper
    ports: ["2181:2181"]
  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports: ["9092:9092"]
  tron-local:
    image: tronprotocol/quickstart
    ports: ["8090:8090","8091:8091"]
